#!/usr/bin/env python3
"""Generate the WebC command table from the compiled multicall binary."""
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess

ROOT = Path(__file__).resolve().parents[1]
os.chdir(ROOT)
VERSION = '1.0.27'
STAGE = ROOT / '.wasix'
STAGE.mkdir(exist_ok=True)
wasm = STAGE / 'coreutils.wasm'
shutil.copyfile(Path(os.environ.get('CARGO_TARGET_DIR', 'target')) /
                'wasm32-wasmer-wasi/release/coreutils.wasm', wasm)
commands = subprocess.check_output(['wasmer', 'run', str(wasm), '--', '--list'], text=True).splitlines()
assert len(commands) == len(set(commands)) and {'tail', 'nohup', 'env'} <= set(commands)
manifest = '''# Generated by wasix/package.py from coreutils --list.
[package]
name = "wasmer/coreutils"
version = "1.0.27"
description = "uutils coreutils 0.13.0 for WASIX"
license = "MIT"
readme = "WASIX.md"
repository = "https://github.com/wasix-org/coreutils"
entrypoint = "coreutils"

[fs]
"/opt/coreutils/licenses" = ".wasix/licenses"

[[module]]
name = "coreutils"
source = ".wasix/coreutils.wasm"
abi = "wasi"
'''
for command in ['coreutils', *commands]:
    manifest += f'\n[[command]]\nname = {json.dumps(command)}\nmodule = "coreutils"\nrunner = "wasi"\n'
(ROOT / 'wasmer.toml').write_text(manifest)
(STAGE / 'commands.json').write_text(json.dumps(commands, indent=2) + '\n')
licenses = STAGE / 'licenses'
shutil.rmtree(licenses, ignore_errors=True)
licenses.mkdir()
metadata = json.loads(subprocess.check_output([
    'cargo', '+wasix', 'metadata', '--locked', '--format-version=1',
    '--filter-platform', 'wasm32-wasmer-wasi', '--no-default-features', '--features', 'feat_wasix']))
notices = []
for package in sorted(metadata['packages'], key=lambda p: (p['name'], p['version'])):
    notices.append({k: package[k] for k in ('name', 'version', 'license')})
    for file in Path(package['manifest_path']).parent.iterdir():
        if file.is_file() and file.name.upper().startswith(('LICENSE', 'LICENCE', 'COPYING', 'UNLICENSE', 'NOTICE')):
            dest = licenses / (package['name'] + '-' + package['version']) / file.name
            dest.parent.mkdir(exist_ok=True)
            shutil.copyfile(file, dest)
(licenses / 'DEPENDENCIES.json').write_text(json.dumps(notices, indent=2) + '\n')
for file in [licenses, *licenses.rglob('*')]:
    os.utime(file, (0, 0))
webc = STAGE / f'coreutils-{VERSION}.webc'
webc.unlink(missing_ok=True)
subprocess.run(['wasmer', 'package', 'build', '.', '--out', str(webc)], check=True)
provenance = {'upstream': 'a6d1eb3835c0f808fa9678e4551df7377bcab8d3',
              'commit': subprocess.check_output(['git', 'rev-parse', 'HEAD'], text=True).strip(),
              'lock_sha256': hashlib.sha256(Path('Cargo.lock').read_bytes()).hexdigest(),
              'rustc': subprocess.check_output(['rustc', '+wasix', '-vV'], text=True),
              'cargo_wasix': subprocess.check_output(['cargo', 'wasix', '--version'], text=True).strip()}
(STAGE / 'provenance.json').write_text(json.dumps(provenance, indent=2) + '\n')
for file in [wasm, webc]:
    print(hashlib.sha256(file.read_bytes()).hexdigest(), file.relative_to(ROOT), file.stat().st_size)
