[package]
name = "wasmer/coreutils"
version = "1.0.25"
license = "MIT"

[[module]]
name = "coreutils"
source = "./target/wasm32-wasmer-wasi/release/coreutils.wasm"

[[command]]
name = "arch"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "base32"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "base64"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "baseenc"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "basename"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "cat"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "chcon"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "chgrp"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "chmod"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "chown"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "chroot"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "cksum"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "comm"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "cp"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "csplit"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "cut"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "date"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "dd"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "df"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "dircolors"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "dirname"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "du"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "echo"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "env"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "expand"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "expr"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "factor"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "false"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "fmt"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "fold"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "groups"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "hashsum"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "head"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "hostid"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "hostname"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "id"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "install"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "join"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "kill"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "link"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "ln"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "logname"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "ls"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "mkdir"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "mkfifo"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "mknod"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "mktemp"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "more"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "mv"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "nice"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "nl"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "nohup"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "nproc"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "numfmt"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "od"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "paste"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "pathchk"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "pinky"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "pr"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "printenv"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "printf"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "ptx"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "pwd"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "readlink"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "realpath"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "relpath"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "rm"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "rmdir"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "runcon"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "seq"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "shred"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "shuf"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "sleep"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "sort"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "split"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "stat"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "stdbuf"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "sum"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "sync"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "tac"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "tail"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "tee"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "test"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "timeout"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "touch"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "tr"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "true"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "truncate"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "tsort"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "tty"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "uname"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "unexpand"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "uniq"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "unlink"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "uptime"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "users"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "wc"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "who"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "whoami"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"

[[command]]
name = "yes"
module = "coreutils"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "coreutils"
